### PR TITLE
Add an example of use in a module

### PR DESCRIPTION
**Pull request by pearofducks**

### CODE REVIEW

**Comment by modosc** [comment]
would you mind enabling `Allow edits from maintainers` so i can push changes here as well?

**Comment by pearofducks** [comment]
Already enabled!

**Comment by modosc** [comment]
thanks! just dug in a bit - this is a bit more complicated than i thought, i'm not going to get to this until tomorrow.

**Comment by pearofducks** [comment]
no problem at all - thanks for looking into it!

**Comment by pearofducks** [comment]
I've cleaned up my reproduction so it aligns with your other examples/tests.

If I manually make the change proposed in `406b233` - then all examples/tests pass.

**Comment by modosc** [comment]
> If I manually make the change proposed in 406b233 - then all examples/tests pass.

thanks - what i'm trying to decide is if i should actually write the module in esm and then use babel to convert it to commonjs, or just hardcode this one file and work around it in the build process or ???.

**Comment by pearofducks** [comment]
Ahh, yeah I understand - it looks like the workaround route is the "messiest" but fastest.

**Pull request closed without merging**
